# Generated by Django 4.1.2 on 2022-10-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
