# Generated by Django 4.1.2 on 2022-10-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'COD'), ('Onlie', 'Online')], default='COD', max_length=55),
        ),
    ]
