# Generated by Django 4.1.2 on 2022-10-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
